### ISSUE TITLE
Tracking numbers no numericos

### ISSUE THREAD

**Issue by llermaly** [josemontesp/correos#1]
Estimado,

Primero que todo felicitarte por la API, es muy noble de tu parte dejarla abierta.

Lo segundo es preguntar cual seria la razon para limitar los tracking number solo a numero siendo que casi todos los que vienen de afuera incluyen letras también 

un saludo

**Comment by josemontesp** [comment]
Hola llermaly,

Gracias por motivarte y abrir el issue!

Tienes toda la razón, hice los cambios correspondientes para que se acepten códigos no numéricos.

El código es abierto y la API también. Está hosteada en Heroku para facilitar el testeo y que se pueda ver rápidamente cómo funciona. No es recomendable usar la instancia que tengo en Heroku en un ambiente de producción.

Saludos!
